server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      file-size-threshold: 5MB
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5  #每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10  #10秒没收到心跳就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

fdfs:
  so-timeout: 2500
  connect-timeout: 600
  thumb-image: # 缩略图
    width: 30
    height: 30
  tracker-list: # tracker地址
    - 192.168.18.135:22122

ly:
  upload:
    baseUrl: http://image.leyou.com/
    allowTypes:
      - image/png
      - image/jpeg